version: '3'

services:
  db:
    image: postgres:13-alpine
    container_name: comebuy_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: comebuy_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d
    networks:
      - internal
networks:
  internal:
